name: Deploy Streamlit App "Invoice Extractor"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - invoice-extractor/**

jobs:
  deploy-invoice-extractor:
    name: Deploy Invoice Extractor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v2

      - name: Create app.yaml
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: invoice-extractor/app.yaml.jinja
          output_file: invoice-extractor/app.yaml
          strict: true
          variables: |
            COHERE_API_KEY=${{ secrets.COHERE_API_KEY }}

      - name: Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Deploy
        id: deploy
        uses: google-github-actions/deploy-appengine@v0
        with:
          deliverables: invoice-extractor/app.yaml

      - name: Healthcheck
        id: curl-api
        run: curl "${{ steps.deploy.outputs.url }}/healthz"

